/** zh-TW 介面文案（役名、牌名保留日文） */
export const S = {
  appTitle: '花牌 こいこい',
  subtitle: '日本花牌對戰',
  start: '開始對戰',
  rounds: '局數',
  roundsUnit: '月',
  aiLevel: 'AI 等級',
  aiLevels: { 1: '初級', 2: '中級', 3: '高級' } as Record<number, string>,
  variants: '規則變體',
  hanamiZake: '花見酒',
  tsukimiZake: '月見酒',
  cardStyle: '卡面風格',
  styleModern: '簡約',
  styleTraditional: '傳統',
  rules: '規則說明',
  history: '對戰紀錄',
  you: '你',
  ai: 'AI',
  round: (n: number, total: number) => `第 ${n} / ${total} 月`,
  oyaMark: '親',
  deckCount: (n: number) => `山札 ${n}`,
  yourTurn: '輪到你出牌',
  aiThinking: 'AI 思考中…',
  chooseMatch: '選擇要配對的場札',
  koikoiTitle: '成役！',
  koikoiPrompt: '要「こいこい」繼續搏更高分，還是「勝負」立即結算？',
  koikoi: 'こいこい！',
  shoubu: '勝負',
  roundWin: (name: string, pts: number) => `${name} 本局獲得 ${pts} 點`,
  roundDraw: '流局 — 無人成役，親續任',
  instantWin: { teshi: '手四！', kuttsuki: 'くっつき！' },
  instantWinDesc: {
    teshi: (name: string) => `${name}發到的手牌中有同一月份的牌 4 張（手四）— 依規則不用打牌，直接獲勝本局並得 6 點。`,
    kuttsuki: (name: string) => `${name}發到的手牌恰好是 4 組同月份對子（くっつき）— 依規則不用打牌，直接獲勝本局並得 6 點。`,
  },
  redealNotice: '場上出現同月份 4 張，重新發牌',
  matchEnd: '對戰結束',
  matchWinner: (name: string) => `${name} 獲勝！`,
  matchDraw: '平手',
  nextRound: '下一局',
  backToMenu: '回主選單',
  playAgain: '再來一場',
  scoreUnit: '點',
  multiplierNames: {
    sevenPointDouble: '7 點以上 ×2',
    koikoiOpponentDouble: '對手こいこい中 ×2',
  } as Record<string, string>,
  captured: {
    hikari: '光', tane: 'タネ', tanzaku: '短冊', kasu: 'カス',
  } as Record<string, string>,
  yakuPanel: '役型進度',
  cheatsheet: '役型速查表',
  close: '關閉',
  exit: '離開',
  continueGame: '繼續對戰',
  achievements: '成就',
  cardDetailHint: '長按或右鍵點牌可看說明',
};
